### ISSUE TITLE
Should I be a contributor?

### ISSUE THREAD

**Issue by uptownhr** [nodeschool/glendora#2]
It appears I do not have write access to this repo. Let me know if I'm wrong but would be awesome for me to be able to write directly. 

I'm trying to readup on it but since I'm a part of the organizers team, shouldn't I be an admin and should be able to write?

**Comment by SomeoneWeird** [comment]
Yep. Totally my bad. You should be able to push to the repo now. :+1:

**Comment by uptownhr** [comment]
thanks!
